$(PLATFORM)NAME= Charge
PLATFORM=centos6
DEPENDENCIES=../sdks
CCDEBUG+= -g
CCOPT+= -O0
#CFLAGS+= -D_CRT_SECURE_NO_DEPRECATE -DBOOST_ALL_NO_LIB
CCWARN+= -Wno-unknown-pragmas -Wno-reorder -Wno-deprecated-declarations -Wno-unused-value
CFLAGS+=  -I./ -I../libkeye/ -I../libimmortal/ -I../libvic/ -I../protocol/ -I$(DEPENDENCIES)/include
LDFLAGS+= -L$(DEPENDENCIES)/libs/$(PLATFORM) -L../protocol/ -Wl,-rpath-link=$(DEPENDENCIES)/libs/$(PLATFORM) -Wl,-rpath=$(DEPENDENCIES)/libs/$(PLATFORM) -Wl,--no-as-needed
LIBS+=  -limmortal -lkeye -lvic -lprotocol -lprotobuf-lite -lmysqlclient -lhiredis -lcurl -lssl -lcrypto -lstdc++ -lm -lboost_system -lboost_date_time
SRCS= $(wildcard *.cpp) \
	$(wildcard openapi/*.cpp) \
	$(wildcard openapi/http/*.cpp) \
	$(wildcard openapi/json/*.cpp) \
	$(wildcard openapi/json/*.c)
INCS= $(wildcard *.h)
