NAME= vic
DEPENDENCIES=../sdks
BUILDMODE=dynamic
CCDEBUG+= -g
CCOPT+= -O0
#CFLAGS+= -D_CRT_SECURE_NO_DEPRECATE -DBOOST_ALL_NO_LIB
CCWARN+= -Wno-unknown-pragmas -Wno-reorder -Wno-deprecated-declarations -Wno-unused-value
CFLAGS+= -I$(DEPENDENCIES)/include -I$(DEPENDENCIES)/include/mysql
LDFLAGS+= -L$(DEPENDENCIES)/libs -Wl,-rpath-link=$(DEPENDENCIES)/libs -Wl,--no-as-needed
LIBS+= -lmysqlclient -lboost_system -lboost_date_time
SRCS= $(wildcard libvic/mysql_proxy/*.cpp) \
	$(wildcard libvic/redis_proxy/*.cpp) \
	$(wildcard libvic/*.cpp)
INCS= $(wildcard libvic/mysql_proxy/*.h) \
	$(wildcard libvic/mysql_proxy/*.hpp) \
	$(wildcard libvic/redis_proxy/*.h) \
	$(wildcard libvic/redis_proxy/*.hpp) \
	$(wildcard libvic/*.h) \
	$(wildcard libvic/*.hpp)
